name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @IsarCollection.
version: 2.4.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  analyzer: ">=4.6.0 <6.0.0"
  build: ^2.3.0
  dart_style: ^2.2.3
  dartx: ^1.1.0
  glob: ^2.0.2
  isar: 2.4.0
  path: ^1.8.1
  source_gen: ^1.2.1

dev_dependencies:
  lints: ^1.0.1
